In [1]:
import numpy as np
import math

In [2]:
x = [[0,0],[0,1],[1,0],[1,1]] #Inputs
N = 4 #Number of hidden layers
yd = [[0],[1],[1],[0]]

In [3]:
def calc_multiquadric(r):# Assuming the constant to be 1
    return(math.sqrt(pow(r,2)+1))

In [4]:
fie = []
for i in range(4): 
    temp = []
    for j in range(4):
        summ = 0
        for k in range(2):
            summ+= abs(x[i][k]-x[j][k])
        num = calc_multiquadric(summ)
        temp.append(num)
    fie.append(temp)
print(fie)


[[1.0, 1.4142135623730951, 1.4142135623730951, 2.23606797749979], [1.4142135623730951, 1.0, 2.23606797749979, 1.4142135623730951], [1.4142135623730951, 2.23606797749979, 1.0, 1.4142135623730951], [2.23606797749979, 1.4142135623730951, 1.4142135623730951, 1.0]]


In [5]:
fie=np.asarray(fie)
print(fie)

[[1.         1.41421356 1.41421356 2.23606798]
 [1.41421356 1.         2.23606798 1.41421356]
 [1.41421356 2.23606798 1.         1.41421356]
 [2.23606798 1.41421356 1.41421356 1.        ]]


In [6]:
fie_inverse = np.linalg.inv(fie) 
print(fie_inverse)

[[ 0.25       -0.5720614  -0.5720614   1.05901699]
 [-0.5720614   0.25        1.05901699 -0.5720614 ]
 [-0.5720614   1.05901699  0.25       -0.5720614 ]
 [ 1.05901699 -0.5720614  -0.5720614   0.25      ]]


In [7]:
w = np.dot(fie_inverse,yd)
print(w)

[[-1.14412281]
 [ 1.30901699]
 [ 1.30901699]
 [-1.14412281]]


In [8]:
f = np.dot(fie,w)
print(f) #which is approximated to yd

[[-4.44089210e-16]
 [ 1.00000000e+00]
 [ 1.00000000e+00]
 [-1.11022302e-15]]
